FROM fedora:27

RUN dnf install -y findutils file cmake gcc gcc-c++ make

ADD TileDB /opt/TileDB

WORKDIR /opt/TileDB
RUN mkdir build \
 && cd build \
 && cmake .. -DCMAKE_BUILD_TYPE=Release \
 && make -j4 \
 && make examples \
 && make check \
 && make -C tiledb install
